### PR TITLE
Randomized Singular Value Decomposition (rsvd)

### PR DESCRIPTION
**Pull request by Benli11**
Works fine... But I will add any-when later a wrap for the cuRAND library, to have access to better random number generators.

### CODE REVIEW

**Comment by lebedov** [comment]
Out of curiosity, why is there a need for curand wrappers? Is there something that isn't adequately exposed via pycuda's curandom module?

**Comment by Benli11** [comment]
The random number generations with pycuda curandom module seems to be very slow, compared to numpy. (But that could be also due to my graphic card... :)

rand_timing

As far as I see, only the following two generators 
> curandom.MRG32k3aRandomNumberGenerator() 
> curandom.XORWOWRandomNumberGenerator()

are supported.  It would be nice to compare it with the 

> CURAND_RNG_PSEUDO_MT19937 and CURAND_RNG_PSEUDO_MTGP32

generators. I assume they are faster, at least according to the NVIDIA doc
http://docs.nvidia.com/cuda/curand/testing.html#testing
but I have no experience with them. 

The  documentation is pointing also the following out:
> 3.5. Performance Notes
>Calls to curand_init() are slower than calls to curand() or curand_uniform(). Large offsets to >curand_init() take more time than smaller offsets. It is much faster to save and restore random >generator state than to recalculate the starting state repeatedly.

But I will talk the week after next to the NVIDIA guys.

**Comment by Benli11** [comment]
Okay, it was my fault. The problem was really the curand_init() I guess, which takes roughly 1s. If I innate only once before the simulation the picture looks quite different!

rand_timing

I guess, this issue is resolved. :)

**Comment by Benli11** [comment]
The rSVD timing (at least) for a square matrix looks promising:

rsvd_timing2

**Comment by lebedov** [comment]
Great - thanks.

**Pull request merged**
