### PR TITLE
add keepdims to sum, var, std, (arg)min, (arg)max

### PR DESCRIPTION
**Pull request by davidweichiang**
This adds the 'keepdims' option found in numpy reductions to some of the reductions in skcuda.misc. (It does not allow axis to be a tuple as numpy reductions do.)

There are also a couple of extra error checks added for 0, 1, or >= 3 dimensional arrays.

### CODE REVIEW

**Comment by lebedov** [comment]
Thanks! Can you please update the docstrings of the modified functions to describe the additional parameter?

**Comment by davidweichiang** [comment]
Sure, I'll do that. I also have a question: currently these functions return a 0-d ndarray for the axis=None case, but a GPUArray for the axis=num case. The distinction becomes more apparent with keepdims=True, because in the axis=None case, the returned ndarray has the same number of dims as the argument. For consistency, can the return value be changed to GPUArray in all cases or will that break your existing code?

**Comment by lebedov** [comment]
@untom, see the previous comment. What do you think?

**Comment by untom** [comment]
You're right, that's an inconsistency in the current API. I don't know how much existing code it will break, but it's probably the right way to do it and probably should've been done this way from the beginning.

**Comment by lebedov** [comment]
I don't have any objection to making the functions consistent. @davidweichiang, if you do so, please

- update the docstrings to properly reflect the correct result type, and
- update the relevant unit tests for the axis=None cases.

Thanks.

**Comment by lebedov** [comment]
Also, feel free to add a short line to the changelog describing the modification.

**Comment by davidweichiang** [comment]
Done!

**Pull request merged**
