### PR TITLE
Fixing magma eigensolver wrappers: sgeev, dgeev, cgeev, zgeev

### PR DESCRIPTION
**Pull request by wingkitlee0**
I have fixed a few interface for geev. I have also included a new demo/test for the magma eigenvalue routines.

### CODE REVIEW

**Comment by lebedov** [comment]
Thanks!

**Comment by TK-21st** [comment]
When running magma_all_geev_demo.py I'm getting the following errors:
```
On entry to magma_cgehrd, parameter 3 had an illegal value (info = -3)
On entry to magma_cunghr, parameter 3 had an illegal value (info = -3)
On entry to magma_sgehrd, parameter 3 had an illegal value (info = -3)
On entry to magma_sorghr, parameter 3 had an illegal value (info = -3)
On entry to magma_dgehrd, parameter 3 had an illegal value (info = -3)
On entry to magma_dorghr, parameter 3 had an illegal value (info = -3)
    'type'      'GPU'      'CPU'   'Equal?'
       'z'       4.42,       1.99,       True
       'c'      0.383,      0.977,      False
       's'      0.233,      0.611,      False
       'd'      0.366,      0.894,      False
```
I'm running scikit-cuda from master ce461c084f675c632fcfa0201a73b0ee4048cb16 with MAGMA-2.2.0 on Python3.7

**Comment by lebedov** [comment]
@TK-21st Tingkai, I encountered no errors when I tried running the demo in revision ce461c0 with Python 3.7.3 and MAGMA 2.5.0 built against CUDA 10.1.

**Comment by TK-21st** [comment]
@lebedov Hi Lev, thanks for the prompt reply. Checked on MAGMA 2.4.0 built agains CUDA 9.1 and error was gone. Likely the issue with the MAGMA 2.2.0 library.

Thank you!

**Comment by wingkitlee0** [comment]
@TK-21st I helped write this part..Glad to know it works! 
On a related note, the demo checks only eigenvalues and you should double-check the eigenvectors. Both array formats (column vs row major, or 'F'/'C' ) in your actual code may give you the same set of eigenvalues. However, only one set of the eigenvectors is what you want.

**Pull request merged**
